### ISSUE TITLE
Included singleuser and systemuser Docker images fail to start jupyterhub-singleuser

### ISSUE THREAD

**Issue by ksolan** [jupyter/dockerspawner#29]
When I build the Docker images included in the repo and use either DockerSpawner or SystemUserSpawner, JupyterHub will create a container on login and wait for it to come up, but it never does:

```
[I 2015-03-31 20:13:06.497 JupyterHub dockerspawner:289] Created container 'jupyter-user1' (id: 0331384) from image jupyter/singleuser
[I 2015-03-31 20:13:06.498 JupyterHub dockerspawner:299] Starting container 'jupyter-user1' (id: 0331384)
[W 2015-03-31 20:13:16.417 JupyterHub base:238] User user server is slow to start
[I 2015-03-31 20:13:16.426 JupyterHub log:100] 302 GET /hub/user/user1/ (user@10.0.0.137) 10037.15ms
[I 2015-03-31 20:13:16.529 JupyterHub log:100] 302 GET /user/user1/ (@10.0.0.137) 0.73ms
[I 2015-03-31 20:13:16.574 JupyterHub log:100] 200 GET /hub/user/user1/ (user1@10.0.0.137) 5.93ms
[W 2015-03-31 20:13:37.026 JupyterHub orm:395] user1's server never showed up at http://localhost:49176/user/user1 after 30 seconds. Giving up
[E 2015-03-31 20:13:37.037 JupyterHub gen:673] Exception in Future <tornado.concurrent.Future object at 0x7f04637bff98> after timeout
    Traceback (most recent call last):
      File "/home/user1/venv3/lib/python3.4/site-packages/tornado/gen.py", line 669, in error_callback
        future.result()
      File "/home/user1/venv3/lib/python3.4/site-packages/jupyterhub/orm.py", line 411, in spawn
        raise e
      File "/home/user1/venv3/lib/python3.4/site-packages/jupyterhub/orm.py", line 387, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/home/user1/venv3/lib/python3.4/site-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/home/user1/venv3/lib/python3.4/site-packages/jupyterhub/utils.py", line 83, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:49176/user/user1 didn't respond in 30 seconds
```

Examining the container's logs shows the problem:
```
$ sudo docker logs jupyter-user1
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 8, in <module>
    from urllib.parse import quote
ImportError: No module named parse
```

urllib.parse is a Python 3 module, and the default 'python' version on the Docker image (and most Ubuntu setups) is 2.7. The `/usr/local/bin/jupyterhub-singleuser` script in the Docker container needs to be run with python3 instead of python.

**Comment by ksolan** [comment]
Submitted a pull request to JupyterHub that solves this issue: https://github.com/jupyter/jupyterhub/pull/217 Alternatively, singleuser.sh and systemuser.sh could be amended to call jupyterhub-singleuser with python3:
```
-jupyterhub-singleuser \
+python3 /usr/local/bin/jupyterhub-singleuser \
```
but I think the fix to JupyterHub is a bit cleaner.
