### ISSUE TITLE
No Attribute _cross_validation_lock

### ISSUE THREAD

**Issue by pulkitag** [jupyter/dockerspawner#37]
I am trying to launch JupyterHub with the Github Authenticator and I am running into the following issue. Any suggestions as to what might be causing this? 

Traceback (most recent call last):
      File "/path/to/dir/jupyterhub/jupyterhub/app.py", line 1063, in launch_instance_async
        yield self.initialize(argv)
      File "/path/to/dir/jupyterhub/jupyterhub/app.py", line 882, in initialize
        yield self.init_spawners()
      File "/path/to/dir/jupyterhub/jupyterhub/app.py", line 682, in init_spawners
        user=user, hub=self.hub, config=self.config, db=self.db,
      File "/path/to/dir/jupyterhub/jupyterhub/spawner.py", line 114, in __init__
        self.load_state(self.user.state)
      File "/usr/local/lib/python3.4/dist-packages/dockerspawner/dockerspawner.py", line 165, in load_state
        self.container_id = state.get('container_id', '')
      File "/usr/local/lib/python3.4/dist-packages/src/traitlets/traitlets/traitlets.py", line 450, in __set__
        new_value = self._validate(obj, value)
      File "/usr/local/lib/python3.4/dist-packages/src/traitlets/traitlets/traitlets.py", line 472, in _validate
        if obj._cross_validation_lock is False:
    AttributeError: 'DockerSpawner' object has no attribute '_cross_validation_lock'

**Comment by minrk** [comment]
This should be fixed by #36. What's the commit of dockerspawner and JupyterHub? (`git log --oneline -1`)

**Comment by pulkitag** [comment]
For dockerspawner:
1dbd962 Merge pull request #36 from EdwardJKim/master

For JupyterHub 
0c16fb9 Merge pull request #257 from minrk/command-traitlet

So I guess, its the version which has #36 fix?

**Comment by minrk** [comment]
What do you get from `pip list`?

**Comment by pulkitag** [comment]
The relevant outputs are:

dockerspawner (0.0.1-dev)
jupyterhub (0.2.0.dev, /path/to/dir/jupyterhub)

Would you like to know the status of any other packages also?

**Comment by minrk** [comment]
Ah, no. JupyterHub is out of date. Update JupyterHub.

**Comment by pulkitag** [comment]
Ah, ok - that resolved it! Thanks.
