### ISSUE TITLE
Unable to start a container - /usr/bin/env: python3: No such file or directory

### ISSUE THREAD

**Issue by vroomanj** [jupyter/dockerspawner#59]
While trying to start a container the jupyterhub server outputs the following:
```
[E 2016-01-13 09:07:42.749 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f50625bbba8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/root/jupyterhub/jupyterhub/user.py", line 231, in spawn
        raise e
      File "/root/jupyterhub/jupyterhub/user.py", line 207, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/root/jupyterhub/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/root/jupyterhub/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:32802/user/admin didn't respond in 30 seconds

```

Checking the Docker logs for the container reports:
```
/usr/bin/env: python3: No such file or directory
```

**Comment by minrk** [comment]
what image are you using?

**Comment by vroomanj** [comment]
Sorry, I should have mentioned that. I am attempting to use the image pulled from Docker Hub.

**Comment by richjoyce** [comment]
I've also got this problem, using the systemuser image

**Comment by richjoyce** [comment]
It looks like the new user created doesn't get the proper `PATH` variable, this is truncated output from `sudo -E -u $USER sh -c export`

```
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

If I modify the script to say `sudo -E PATH="/opt/conda/bin:$PATH" -u $USER ...` then it gets past this error and runs the notebook but more problems occur, with a connection causing a bunch of exceptions. Not sure if this is related or not to the root issue.

**Comment by minrk** [comment]
That's probably on the right track. I bet it's a change in the upstream image.

**Comment by minrk** [comment]
This should be working after #62

**Comment by richjoyce** [comment]
I can't get it to work, either singleuser or systemuser. I had to make a modification for systemuser (#63) but when I try to login to jupyterhub the jupyter docker crashes. Here is a short version of the log:
```
/opt/conda/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
[I 2016-01-15 21:05:24.282 testing notebookapp:499] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 2016-01-15 21:05:24.584 testing notebookapp:1063] Serving notebooks from local directory: /home/jovyan/work
[I 2016-01-15 21:05:24.586 testing notebookapp:1063] 0 active kernels
[I 2016-01-15 21:05:24.591 testing notebookapp:1063] The IPython Notebook is running at: http://0.0.0.0:8888/user/testing/
[I 2016-01-15 21:05:24.593 testing notebookapp:1064] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2016-01-15 21:05:24.614 testing log:47] 302 GET /user/testing (172.17.0.1) 10.53ms
[I 2016-01-15 21:05:24.680 testing log:47] 302 GET /user/testing/ (192.168.56.1) 0.97ms
[E 2016-01-15 21:05:24.721 testing web:1524] Uncaught exception GET /user/testing/tree (192.168.56.1)
    HTTPServerRequest(protocol='http', host='192.168.56.101:8000', method='GET', uri='/user/testing/tree', version='HTTP/1.1', remote_ip='192.168.56.1', headers={'X-Forwarded-Port': '8000', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Forwarded-Proto': 'http', 'Referer': 'http://192.168.56.101:8000/hub/home', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'X-Forwarded-For': '192.168.56.1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Host': '192.168.56.101:8000', 'Accept-Language': 'en-US,en;q=0.8', 'Connection': 'close', 'Cookie': 'jupyter-hub-token-testing="2|1:0|10:1452891924|25:jupyter-hub-token-testing|44:OGMwOWFhYzA4MTkzNDNiZTg1NWQxYjAwOTA1OGY0MmU=|747461b044b1cf193e63e870259bd34a99f4e7cf82fdaf274ddf611681f4ea9a"'})
    Traceback (most recent call last):
...
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7fc0c86e57b8> is not JSON serializable
```
