### ISSUE TITLE
'NoneType' object is not subscriptable getting container port

### ISSUE THREAD

**Issue by vroomanj** [jupyter/dockerspawner#71]
I went from 0.0.1.dev to 0.2.0.dev and get the following traceback:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/usr/local/jupyterhub/jupyterhub/handlers/login.py", line 72, in post
        yield self.spawn_single_user(user)
      File "/usr/local/jupyterhub/jupyterhub/handlers/base.py", line 296, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/jupyterhub/jupyterhub/user.py", line 202, in spawn
        raise e
      File "/usr/local/jupyterhub/jupyterhub/user.py", line 183, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/jupyterhub/swarmspawner.py", line 59, in start
        extra_host_config=extra_host_config)
      File "/usr/local/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 391, in start
        ip, port = yield from self.get_ip_and_port()
      File "/usr/local/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 407, in get_ip_and_port
        port = resp[0]['HostPort']
    TypeError: 'NoneType' object is not subscriptable

It seems (looking at the Docker image logs) that none of the JupyterHub info such as $USER and $USER_ID are getting passed into the container and the container then fails to start.

**Comment by minrk** [comment]
That mean that `docker port` is returning no info. @rgbkrk do you know why that would be?

**Comment by rgbkrk** [comment]
If a container gets started but fails to run, that's one way that `docker port` returns no info.

**Comment by minrk** [comment]
#75 should give a better error message. #76 should actually fix the missing env
